services:
  - type: web
    runtime: static
    name: citizens-council
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    headers:
      - path: /_astro/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /**/*.webp
        name: Cache-Control
        value: public, max-age=604800, stale-while-revalidate=86400
      - path: /**/*.png
        name: Cache-Control
        value: public, max-age=604800, stale-while-revalidate=86400
      - path: /**/*.jpg
        name: Cache-Control
        value: public, max-age=604800, stale-while-revalidate=86400
      - path: /**/*.jpeg
        name: Cache-Control
        value: public, max-age=604800, stale-while-revalidate=86400
